# Generated by Django 3.0.6 on 2020-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeafModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.TextField(default='')),
                ('is_preprocessed', models.BooleanField(default=False)),
                ('preprocessed_image', models.TextField(default='')),
                ('aspect_ratio', models.FloatField(default=0.0)),
                ('rectangularity', models.FloatField(default=0.0)),
                ('perimeter_ratio', models.FloatField(default=0.0)),
                ('compactness', models.FloatField(default=0.0)),
                ('mean_color', models.CharField(default='#000000', max_length=7)),
                ('vein_area_2_ratio', models.FloatField(default=0.0)),
                ('vein_area_4_ratio', models.FloatField(default=0.0)),
                ('elongation', models.FloatField(default=0.0)),
                ('variety', models.TextField(choices=[('alphonso', 'Alphonso'), ('amrapali', 'Amrapali'), ('chaunsa', 'Chaunsa'), ('dusheri', 'Dusheri'), ('langra', 'Langra')])),
            ],
        ),
    ]
